### ISSUE TITLE
🦵 Footer

### ISSUE THREAD

**Issue by JustinLung** [JustinLung/saml-zelftestapp-campaign-website#1]
Als gebruiker wil ik een footer met links naar de verschillende secties van de website, zodat ik makkelijker kan navigeren door de website heen.

Requirements

- [x] Links naar andere delen van de site
- [x]  Footer titel toevoegen 
- [x] Definition of done

**Comment by JustinLung** [comment]
@DphnZwp Ready for testing

**Comment by DphnZwp** [comment]
@JustinLung Ready for merging
