### ISSUE TITLE
💯  Benodigheden Section

### ISSUE THREAD

**Issue by JustinLung** [JustinLung/saml-zelftestapp-campaign-website#14]
Als gebruiker wil de benodigheden van de app, zodat ik een kleine uitleg krijg over de app hoe deze werkt. 

Requirements:
- [ ] Content vullen
- [ ] In een Grid Layout
- [ ] Definition of done

**Comment by JustinLung** [comment]
@DphnZwp the HTML for the cards is not semantic. You have a div named grid-container. But the styling on the grid container can be done on the section. Maybe fix this? Also, you have a card.css file. Maybe put this in the style.css file, so every CSS is on the same file!

**Comment by DphnZwp** [comment]
I have removed the grid-container div and put everything in the main css. I also forgot to fill in the alt for the images. So I solved that too.
