### ISSUE TITLE
🦸 Hero Section

### ISSUE THREAD

**Issue by JustinLung** [JustinLung/saml-zelftestapp-campaign-website#4]
Als gebruiker, wil ik de hero section zien, zodat ik me verwelkomd voel wanneer ik op de website kom.

Requirements

- [x] Heading
- [x] Subtekst
- [x] CTA naar web app
- [x] CTA scroll naar about
- [x] Definition of done

**Comment by JustinLung** [comment]
@DphnZwp Ready for testing

**Comment by DphnZwp** [comment]
@JustinLung Ready for merging
