### ISSUE TITLE
🈂️ Service Section

### ISSUE THREAD

**Issue by JustinLung** [JustinLung/saml-zelftestapp-campaign-website#7]
Als gebruiker wil ik de diensten zien die de ScanMyTest App dient, zodat ik een beter begrip krijg wat de app doet.

Requirement

- [x] In een row layout
- [x] Content voor de kaarten
- [x] Definition of done

**Comment by JustinLung** [comment]
Ready for testing

**Comment by M4TThys123** [comment]
Ready for merge!
